version: "3.9"

services:
  db:
    image: postgres
    networks:
      - bot_network
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - "8001:5432"
  bot:
    build: .
    networks:
      - bot_network
    environment:
      - DB_POSTGRES=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - DB_PORT=5432
    command: python main.py
    volumes:
      - ./main.py:/bot/main.py
      - ./apps:/bot/apps
      - ./configs:/bot/configs
    depends_on:
      - db

networks:
  bot_network:
    driver: bridge